services:
    app:
        build: .
        container_name: aiqfome-api
        ports:
            - '${APP_PORT}:${APP_PORT}'
        env_file:
            - .env
        depends_on:
            - db
    db:
        image: postgres:14-alpine
        container_name: aiqfome-db
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}
        restart: always
        ports:
            - '${DB_PORT}:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
    redis:
        image: redis:7-alpine
        ports:
            - '${REDIS_PORT}:6379'
volumes:
    postgres_data:
